# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'actorsMenu.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.backBtn = QtWidgets.QPushButton(self.centralwidget)
        self.backBtn.setGeometry(QtCore.QRect(40, 477, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.backBtn.setFont(font)
        self.backBtn.setObjectName("backBtn")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(160, 80, 371, 421))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.addActorBtn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.addActorBtn.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.addActorBtn.setFont(font)
        self.addActorBtn.setObjectName("addActorBtn")
        self.verticalLayout.addWidget(self.addActorBtn)
        self.showActorBtn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.showActorBtn.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.showActorBtn.setFont(font)
        self.showActorBtn.setObjectName("showActorBtn")
        self.verticalLayout.addWidget(self.showActorBtn)
        self.findActorBtn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.findActorBtn.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.findActorBtn.setFont(font)
        self.findActorBtn.setObjectName("findActorBtn")
        self.verticalLayout.addWidget(self.findActorBtn)
        self.editActorBtn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.editActorBtn.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.editActorBtn.setFont(font)
        self.editActorBtn.setObjectName("editActorBtn")
        self.verticalLayout.addWidget(self.editActorBtn)
        self.delActorBtn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.delActorBtn.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.delActorBtn.setFont(font)
        self.delActorBtn.setObjectName("delActorBtn")
        self.verticalLayout.addWidget(self.delActorBtn)
        self.truncateActorBtn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.truncateActorBtn.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.truncateActorBtn.setFont(font)
        self.truncateActorBtn.setObjectName("truncateActorBtn")
        self.verticalLayout.addWidget(self.truncateActorBtn)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(250, 20, 191, 71))
        self.label.setMinimumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.backBtn.setText(_translate("MainWindow", "Назад"))
        self.addActorBtn.setText(_translate("MainWindow", "Добавить новое поле"))
        self.showActorBtn.setText(_translate("MainWindow", "Вывести таблицу"))
        self.findActorBtn.setText(_translate("MainWindow", "Найти по"))
        self.editActorBtn.setText(_translate("MainWindow", "Редактировать поле"))
        self.delActorBtn.setText(_translate("MainWindow", "Удалить поле"))
        self.truncateActorBtn.setText(_translate("MainWindow", "Очистить таблицу"))
        self.label.setText(_translate("MainWindow", "таблица: Actors"))
