# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addMenuShow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(643, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(40, 40, 491, 461))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.labelNmae = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelNmae.setFont(font)
        self.labelNmae.setObjectName("labelNmae")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelNmae)
        self.textboxName = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.textboxName.setFont(font)
        self.textboxName.setObjectName("textboxName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.textboxName)
        self.labelCountry = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelCountry.setFont(font)
        self.labelCountry.setObjectName("labelCountry")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelCountry)
        self.textboxCountry = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.textboxCountry.setFont(font)
        self.textboxCountry.setObjectName("textboxCountry")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.textboxCountry)
        self.spinBoxSeasons = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.spinBoxSeasons.setObjectName("spinBoxSeasons")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.spinBoxSeasons)
        self.labelSeasons = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelSeasons.setFont(font)
        self.labelSeasons.setObjectName("labelSeasons")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelSeasons)
        self.spinBoxWatched = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.spinBoxWatched.setObjectName("spinBoxWatched")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.spinBoxWatched)
        self.spinBoxEpisodes = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.spinBoxEpisodes.setObjectName("spinBoxEpisodes")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.spinBoxEpisodes)
        self.labelEpisodes = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelEpisodes.setFont(font)
        self.labelEpisodes.setObjectName("labelEpisodes")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.labelEpisodes)
        self.labelWatched = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelWatched.setFont(font)
        self.labelWatched.setObjectName("labelWatched")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.labelWatched)
        self.checkBtn = QtWidgets.QPushButton(self.centralwidget)
        self.checkBtn.setGeometry(QtCore.QRect(430, 280, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.checkBtn.setFont(font)
        self.checkBtn.setObjectName("checkBtn")
        self.errorLabel = QtWidgets.QLabel(self.centralwidget)
        self.errorLabel.setGeometry(QtCore.QRect(30, 280, 391, 31))
        self.errorLabel.setText("")
        self.errorLabel.setObjectName("errorLabel")
        self.backBtn = QtWidgets.QPushButton(self.centralwidget)
        self.backBtn.setGeometry(QtCore.QRect(30, 280, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.backBtn.setFont(font)
        self.backBtn.setObjectName("backBtn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 643, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelNmae.setText(_translate("MainWindow", "Название:"))
        self.labelCountry.setText(_translate("MainWindow", "Страна"))
        self.labelSeasons.setText(_translate("MainWindow", "Количество сезонов"))
        self.labelEpisodes.setText(_translate("MainWindow", "Количетво серий "))
        self.labelWatched.setText(_translate("MainWindow", "Просмотрено"))
        self.checkBtn.setText(_translate("MainWindow", "Готово"))
        self.backBtn.setText(_translate("MainWindow", "Назад"))
