# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addMenuActor.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(643, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(40, 40, 491, 461))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.labelName = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelName.setFont(font)
        self.labelName.setObjectName("labelName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelName)
        self.textboxName = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.textboxName.setFont(font)
        self.textboxName.setObjectName("textboxName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.textboxName)
        self.labelCharacterName = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelCharacterName.setFont(font)
        self.labelCharacterName.setObjectName("labelCharacterName")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelCharacterName)
        self.textboxCharacterName = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.textboxCharacterName.setFont(font)
        self.textboxCharacterName.setObjectName("textboxCharacterName")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.textboxCharacterName)
        self.labelShowId = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelShowId.setFont(font)
        self.labelShowId.setObjectName("labelShowId")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelShowId)
        self.spinBoxShowId = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.spinBoxShowId.setObjectName("spinBoxShowId")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.spinBoxShowId)
        self.checkBtn = QtWidgets.QPushButton(self.centralwidget)
        self.checkBtn.setGeometry(QtCore.QRect(430, 280, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.checkBtn.setFont(font)
        self.checkBtn.setObjectName("checkBtn")
        self.errorLabel = QtWidgets.QLabel(self.centralwidget)
        self.errorLabel.setGeometry(QtCore.QRect(30, 280, 391, 31))
        self.errorLabel.setText("")
        self.errorLabel.setObjectName("errorLabel")
        self.backBtn = QtWidgets.QPushButton(self.centralwidget)
        self.backBtn.setGeometry(QtCore.QRect(30, 280, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.backBtn.setFont(font)
        self.backBtn.setObjectName("backBtn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 643, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelName.setText(_translate("MainWindow", "Имя:"))
        self.labelCharacterName.setText(_translate("MainWindow", "Имя персонажа:"))
        self.labelShowId.setText(_translate("MainWindow", "id show"))
        self.checkBtn.setText(_translate("MainWindow", "Готово"))
        self.backBtn.setText(_translate("MainWindow", "Назад"))
