# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editShow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.backBtn = QtWidgets.QPushButton(self.centralwidget)
        self.backBtn.setGeometry(QtCore.QRect(20, 477, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.backBtn.setFont(font)
        self.backBtn.setObjectName("backBtn")
        self.checkBtn = QtWidgets.QPushButton(self.centralwidget)
        self.checkBtn.setGeometry(QtCore.QRect(670, 480, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.checkBtn.setFont(font)
        self.checkBtn.setObjectName("checkBtn")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 30, 401, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.idLine = QtWidgets.QLineEdit(self.centralwidget)
        self.idLine.setGeometry(QtCore.QRect(50, 90, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.idLine.setFont(font)
        self.idLine.setText("")
        self.idLine.setObjectName("idLine")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 150, 351, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.errorLabel = QtWidgets.QLabel(self.centralwidget)
        self.errorLabel.setGeometry(QtCore.QRect(160, 370, 431, 141))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.errorLabel.setFont(font)
        self.errorLabel.setText("")
        self.errorLabel.setObjectName("errorLabel")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(30, 200, 491, 191))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.labelNmae = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelNmae.setFont(font)
        self.labelNmae.setObjectName("labelNmae")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelNmae)
        self.textboxName = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.textboxName.setFont(font)
        self.textboxName.setObjectName("textboxName")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.textboxName)
        self.labelCountry = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelCountry.setFont(font)
        self.labelCountry.setObjectName("labelCountry")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelCountry)
        self.textboxCountry = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.textboxCountry.setFont(font)
        self.textboxCountry.setObjectName("textboxCountry")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.textboxCountry)
        self.spinBoxSeasons = QtWidgets.QSpinBox(self.formLayoutWidget_2)
        self.spinBoxSeasons.setObjectName("spinBoxSeasons")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.spinBoxSeasons)
        self.labelSeasons = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelSeasons.setFont(font)
        self.labelSeasons.setObjectName("labelSeasons")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelSeasons)
        self.spinBoxWatched = QtWidgets.QSpinBox(self.formLayoutWidget_2)
        self.spinBoxWatched.setObjectName("spinBoxWatched")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.spinBoxWatched)
        self.spinBoxEpisodes = QtWidgets.QSpinBox(self.formLayoutWidget_2)
        self.spinBoxEpisodes.setObjectName("spinBoxEpisodes")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.spinBoxEpisodes)
        self.labelEpisodes = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelEpisodes.setFont(font)
        self.labelEpisodes.setObjectName("labelEpisodes")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.labelEpisodes)
        self.labelWatched = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelWatched.setFont(font)
        self.labelWatched.setObjectName("labelWatched")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.labelWatched)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.backBtn.setText(_translate("MainWindow", "Назад"))
        self.checkBtn.setText(_translate("MainWindow", "Готово"))
        self.label.setText(_translate("MainWindow", "Введите id поля, которое хотите изменить"))
        self.label_2.setText(_translate("MainWindow", "Введите значения для изменения"))
        self.labelNmae.setText(_translate("MainWindow", "Название:"))
        self.labelCountry.setText(_translate("MainWindow", "Страна"))
        self.labelSeasons.setText(_translate("MainWindow", "Количество сезонов"))
        self.labelEpisodes.setText(_translate("MainWindow", "Количетво серий "))
        self.labelWatched.setText(_translate("MainWindow", "Просмотрено"))
