# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainMenu.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(465, 625)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(40, 20, 401, 491))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.showBtn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.showBtn.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.showBtn.setFont(font)
        self.showBtn.setMouseTracking(True)
        self.showBtn.setObjectName("showBtn")
        self.verticalLayout.addWidget(self.showBtn)
        self.addBtn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.addBtn.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.addBtn.setFont(font)
        self.addBtn.setMouseTracking(True)
        self.addBtn.setObjectName("addBtn")
        self.verticalLayout.addWidget(self.addBtn)
        self.editBtn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.editBtn.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.editBtn.setFont(font)
        self.editBtn.setMouseTracking(True)
        self.editBtn.setObjectName("editBtn")
        self.verticalLayout.addWidget(self.editBtn)
        self.findBtn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.findBtn.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.findBtn.setFont(font)
        self.findBtn.setMouseTracking(True)
        self.findBtn.setObjectName("findBtn")
        self.verticalLayout.addWidget(self.findBtn)
        self.importBtn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.importBtn.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.importBtn.setFont(font)
        self.importBtn.setMouseTracking(True)
        self.importBtn.setObjectName("importBtn")
        self.verticalLayout.addWidget(self.importBtn)
        self.backBtn = QtWidgets.QPushButton(self.centralwidget)
        self.backBtn.setGeometry(QtCore.QRect(30, 530, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.backBtn.setFont(font)
        self.backBtn.setObjectName("backBtn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 465, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.showBtn.setText(_translate("MainWindow", "Вывести базу данных"))
        self.addBtn.setText(_translate("MainWindow", "Добавить новую запись"))
        self.editBtn.setText(_translate("MainWindow", "Редактировать запись"))
        self.findBtn.setText(_translate("MainWindow", "Поиск по полям"))
        self.importBtn.setText(_translate("MainWindow", "Удалить таблицу"))
        self.backBtn.setText(_translate("MainWindow", "Назад"))
