# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'showMenu.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.backBtn = QtWidgets.QPushButton(self.centralwidget)
        self.backBtn.setGeometry(QtCore.QRect(40, 477, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.backBtn.setFont(font)
        self.backBtn.setObjectName("backBtn")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(170, 90, 371, 431))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.addShowBtn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.addShowBtn.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.addShowBtn.setFont(font)
        self.addShowBtn.setObjectName("addShowBtn")
        self.verticalLayout.addWidget(self.addShowBtn)
        self.showShowBtn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.showShowBtn.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.showShowBtn.setFont(font)
        self.showShowBtn.setObjectName("showShowBtn")
        self.verticalLayout.addWidget(self.showShowBtn)
        self.searchShowBtn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.searchShowBtn.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.searchShowBtn.setFont(font)
        self.searchShowBtn.setObjectName("searchShowBtn")
        self.verticalLayout.addWidget(self.searchShowBtn)
        self.editShowBtn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.editShowBtn.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.editShowBtn.setFont(font)
        self.editShowBtn.setObjectName("editShowBtn")
        self.verticalLayout.addWidget(self.editShowBtn)
        self.delShowBtn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.delShowBtn.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.delShowBtn.setFont(font)
        self.delShowBtn.setObjectName("delShowBtn")
        self.verticalLayout.addWidget(self.delShowBtn)
        self.truncateShowBtn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.truncateShowBtn.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.truncateShowBtn.setFont(font)
        self.truncateShowBtn.setObjectName("truncateShowBtn")
        self.verticalLayout.addWidget(self.truncateShowBtn)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(250, 20, 191, 71))
        self.label.setMinimumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.backBtn.setText(_translate("MainWindow", "Назад"))
        self.addShowBtn.setText(_translate("MainWindow", "Добавить новое поле"))
        self.showShowBtn.setText(_translate("MainWindow", "Вывести таблицу"))
        self.searchShowBtn.setText(_translate("MainWindow", "Найти по "))
        self.editShowBtn.setText(_translate("MainWindow", "Редактировать поле"))
        self.delShowBtn.setText(_translate("MainWindow", "Удалить поле"))
        self.truncateShowBtn.setText(_translate("MainWindow", "Очистить таблицу"))
        self.label.setText(_translate("MainWindow", "таблица: NetflixShow"))
